/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
        
public class f_Utama extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public f_Utama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_kiri = new javax.swing.JPanel();
        p_logo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_sideBar = new javax.swing.JPanel();
        p_kanan = new javax.swing.JPanel();
        p_atas = new javax.swing.JPanel();
        p_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        p_kiri.setBackground(new java.awt.Color(102, 102, 255));

        p_logo.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout p_logoLayout = new javax.swing.GroupLayout(p_logo);
        p_logo.setLayout(p_logoLayout);
        p_logoLayout.setHorizontalGroup(
            p_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        p_logoLayout.setVerticalGroup(
            p_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        p_sideBar.setBackground(new java.awt.Color(102, 102, 255));
        p_sideBar.setLayout(new javax.swing.BoxLayout(p_sideBar, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(p_sideBar);

        javax.swing.GroupLayout p_kiriLayout = new javax.swing.GroupLayout(p_kiri);
        p_kiri.setLayout(p_kiriLayout);
        p_kiriLayout.setHorizontalGroup(
            p_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        p_kiriLayout.setVerticalGroup(
            p_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_kiriLayout.createSequentialGroup()
                .addComponent(p_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
        );

        getContentPane().add(p_kiri, java.awt.BorderLayout.LINE_START);

        p_kanan.setLayout(new java.awt.BorderLayout());

        p_atas.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout p_atasLayout = new javax.swing.GroupLayout(p_atas);
        p_atas.setLayout(p_atasLayout);
        p_atasLayout.setHorizontalGroup(
            p_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        p_atasLayout.setVerticalGroup(
            p_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        p_kanan.add(p_atas, java.awt.BorderLayout.PAGE_START);

        p_content.setLayout(new java.awt.BorderLayout());
        p_kanan.add(p_content, java.awt.BorderLayout.CENTER);

        getContentPane().add(p_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        p_content.removeAll();
        p_content.add(new p_Dashboard());
        p_content.repaint();
        p_content.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_atas;
    private javax.swing.JPanel p_content;
    private javax.swing.JPanel p_kanan;
    private javax.swing.JPanel p_kiri;
    private javax.swing.JPanel p_logo;
    private javax.swing.JPanel p_sideBar;
    // End of variables declaration//GEN-END:variables

private void execute() {
        //Icon Menu Utama
        ImageIcon iconLaporan                         = new ImageIcon(getClass().getResource("/Icon/dashboard_putih.png"));
//        ImageIcon iconUser                            = new ImageIcon(getClass().getResource("/Img/IconBagian.png"));
//        ImageIcon iconLogout                          = new ImageIcon(getClass().getResource("/Img/IconKategori.png"));

        //Icon Sub Menu
        ImageIcon iconLaporanTrk                      = new ImageIcon(getClass().getResource("/Icon/dashboard_putih.png"));
        ImageIcon iconLaporanPendapatan               = new ImageIcon(getClass().getResource("/Icon/dashboard_putih.png"));

        //Mengeksekusi SubMenu
        p_Menu menuSubLapTrk                        = new p_Menu(null, true, iconLaporanTrk, "Lap. Transaksi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        p_Menu menuSubLapPendapatan                 = new p_Menu(null, true, iconLaporanTrk, "Lap. Pendapatan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        //Mengeksekusi Menu Utama
        p_Menu menuDashboard                        = new p_Menu(iconLaporan, false, null, "DASHBOARD", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                p_content.removeAll();
                p_content.add(new p_Dashboard());
                p_content.repaint();
                p_content.revalidate();
            }
        });
        
       p_Menu menuKategori                         = new p_Menu(iconLaporan, false, null, "KATEGORI", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                p_content.removeAll();
                p_content.add(new p_KategoriProduk());
                p_content.repaint();
                p_content.revalidate();
            }
        }); 
        
        p_Menu menuProduk                           = new p_Menu(iconLaporan, false, null, "PRODUK", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        p_Menu menuTransaksi                        = new p_Menu(iconLaporan, false, null, "TRANSAKSI", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        p_Menu menuLaporan                          = new p_Menu(iconLaporan, false, null, "LAPORAN", null, menuSubLapTrk, menuSubLapPendapatan);
        
        p_Menu menuUser                             = new p_Menu(iconLaporan, false, null, "USER", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        p_Menu menuLogout                           = new p_Menu(iconLaporan, false, null, "LOGOUT", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        addMenu(menuDashboard, menuKategori, menuProduk, menuTransaksi,menuLaporan, menuUser, menuLogout);
    }
    
    private void addMenu(Main.p_Menu... menu) {
        for (int i = 0; i < menu.length; i++) {
            p_sideBar.add(menu[i]);
            ArrayList<p_Menu> subMenu = menu[i].getSubMenu();
            for (p_Menu m : subMenu) {
                addMenu(m);
            }
        }
        p_sideBar.revalidate();
    }
}
